name: Add new issues to DevTools project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/hirosystems/projects/15
          github-token: ${{ secrets.GH_TOKEN }}
