name: pre-run
on:
  workflow_call:
    outputs:
      is-not-fork:
        description: "Is the repository the original project"
        value: ${{ jobs.check-fork.outputs.is_not_fork }}

  workflow_dispatch:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  check-fork:
    runs-on: ubuntu-latest
    outputs:
      is_not_fork: ${{ steps.check.outputs.is_not_fork }}
    steps:
      - id: check
        run: echo "::set-output name=is_not_fork::${{ env.NPM_TOKEN != '' }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
